weather.api.key=37d95854b4fc4298a6a230659260607
weather.api.url=https://api.weatherapi.com/v1
weather.api.location=CABA
twilio.auth.token=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
twilio.from.email=ahuarca@frba.utn.edu.ar