weather.api.key=37d95854b4fc4298a6a230659260607
weather.api.url=https://api.weatherapi.com/v1
weather.api.location=CABA
twilio.auth.token= API_KEY_DE_SENDGRID
twilio.from.email=ahuarca@frba.utn.edu.ar